---
- name: Configure NAT rules
  paloaltonetworks.panos.panos_nat_rule:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ panos_username }}"
      password: "{{ panos_password }}"
    vsys: "{{ panos_vsys }}"
    rule_name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    tag_name: "{{ item.tags | default([]) }}"
    source_zone: "{{ item.source_zones }}"
    destination_zone: "{{ item.destination_zone }}"
    service: "{{ item.service | default('any') }}"
    source_ip: "{{ item.source_addresses | default(['any']) }}"
    destination_ip: "{{ item.destination_addresses | default(['any']) }}"
    snat_type: "{{ item.translated_source_type | default('dynamic-ip-and-port') }}"
    snat_interface: "{{ item.translated_source_interface | default(omit) }}"
    dnat_address: "{{ item.translated_destination_address | default(omit) }}"
    dnat_port: "{{ item.translated_destination_port | default(omit) }}"
    state: present
  loop: "{{ panos_nat_rules | default([]) }}"
  when: panos_nat_rules is defined
  no_log: true
