---
all:
  children:

    cisco_meraki:
      hosts:
        meraki_dashboard:
          ansible_connection: local

    cisco_sdwan:
      hosts:
        vmanage_controller:
          ansible_host: "{{ vmanage_host }}"
          ansible_connection: local

    paloalto:
      hosts:
        panorama:
          ansible_host: "{{ panorama_host }}"
          ansible_connection: local

        pa_fw_01:
          ansible_host: "{{ pa_fw_01_host }}"
          ansible_connection: local
